version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - SMITHERY_API_KEY=${SMITHERY_API_KEY}
      - ANDISEARCH_API_KEY=${ANDISEARCH_API_KEY}
      - ENVIRONMENT=development
    volumes:
      - ./src:/app/src
    command: uvicorn mcpsquared_discovery.main:app --host 0.0.0.0 --port 8000 --reload
    